service: catvotes

frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  memorySize: 128
  timeout: 5
  
#  stage: dev
  region: us-east-1
  environment:
        TABLE_NAME: votes-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - Fn::GetAtt:
          - VotesDynamoDbTable
          - Arn

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  votes:
    handler: bin/votes
    events:
      - http:
          path: votes
          method: post
          cors: true
resources:
  Resources:
    VotesDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: image_id
            AttributeType: S  
        KeySchema:
          - AttributeName: image_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'votes-${opt:stage, self:provider.stage}'
